DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `customers`;
DROP TABLE IF EXISTS `services`;
DROP TABLE IF EXISTS `products`;
DROP TABLE IF EXISTS `appointments`;
DROP TABLE IF EXISTS `settings`;
CREATE TABLE `users` (`uid` int(100) NOT NULL AUTO_INCREMENT,`username` varchar(100) DEFAULT NULL,`password` varchar(100) DEFAULT NULL,`email` varchar(100) DEFAULT NULL,`phone` int(100) DEFAULT NULL,`ssid` varchar(100) DEFAULT NULL,PRIMARY KEY (`uid`)) ENGINE=MyISAM DEFAULT CHARSET=utf8;
INSERT INTO `users` VALUES (1,'username','password','test@test.test',1234567890,'1111111111');
CREATE TABLE `customers` (`id` int(11) NOT NULL AUTO_INCREMENT,`fname` varchar(100) DEFAULT NULL,`lname` varchar(100) DEFAULT NULL,`email` varchar(100) DEFAULT NULL,`phone` varchar(100) DEFAULT NULL,`active` tinyint(1) DEFAULT 1,PRIMARY KEY (`id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE `services` (`id` int(11) NOT NULL AUTO_INCREMENT,`name` varchar(100) DEFAULT NULL,`price` varchar(100) DEFAULT NULL, `duration` varchar(100) DEFAULT NULL,`active` tinyint(1) NOT NULL DEFAULT 1,PRIMARY KEY (`id`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;
CREATE TABLE `products` (`id` int(11) NOT NULL AUTO_INCREMENT,`name` varchar(100) COLLATE utf8_bin DEFAULT NULL,`price` varchar(100) COLLATE utf8_bin DEFAULT NULL,`stock` varchar(100) COLLATE utf8_bin DEFAULT NULL,`active` tinyint(1) NOT NULL DEFAULT 1,PRIMARY KEY (`id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
CREATE TABLE `appointments` (`id` int(11) NOT NULL AUTO_INCREMENT,`cid` varchar(100) DEFAULT NULL,`items` varchar(100) DEFAULT NULL,`date` varchar(100) DEFAULT NULL,`duration` varchar(100) DEFAULT NULL,`status` int(11) DEFAULT 1,`eid` int(11) DEFAULT NULL,PRIMARY KEY (`id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE `settings` (`dayoffset` int(11) DEFAULT NULL, `daystoshow` int(11) DEFAULT NULL, `interval` int(11) DEFAULT NULL, `open` int(11) DEFAULT NULL, `close` int(11) DEFAULT NULL ) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;
INSERT INTO `settings` VALUES (0, 7, 15, 540, 1020);